<?php

namespace WebManagementBundle\Repository;
use WebManagementBundle\Entity\Envio;
//use WebManagementBundle\Entity\Empresa;

/**
 * EnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvioRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Para crear un nuevo aviso
     * @param $entityManager
     * @param $empresa
     * @param $comentario
     * @param $usuario
     */
    function CrearNuevo($entityManager, $empresa, $comentario, $usuario){
        $envio = new Envio();
        $envio->setFecha(new \DateTime);
        $envio->setEmpresa($empresa);
        $envio->setUsuario($usuario);
        $envio->setComentario($comentario);

        $entityManager->persist($envio);
        $entityManager->flush();
    }
}
