<?php

namespace WebManagementBundle\Repository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\Entity;
use WebManagementBundle\Entity\Envio;
use WebManagementBundle\Entity\Empresa;


/**
 * EnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvioRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Para crear un nuevo aviso
     * @param $entityManager
     * @param $empresa
     * @param $comentario
     * @param $usuario
     */
    function CrearNuevo($entityManager, $empresa, $comentario, $usuario){
        $envio = new Envio();
        $envio->setFecha(new \DateTime);
        $envio->setEmpresa($empresa);
        $envio->setUsuario($usuario);
        $envio->setComentario($comentario);

        $entityManager->persist($envio);
        $entityManager->flush();
    }

    /**
     * Function que nos devuelve las empresas que no tienen envios
     * @param EntityManager $entity
     * @param $usuario
     * @return array|int|string
     */
    function GetEmpresasSinEnvios(EntityManager $entity, $usuario){
        $qb = $entity->createQuery(
            'SELECT em
                FROM WebManagementBundle:Empresa em
                left join WebManagementBundle:Envio en
                with em.id = en.empresa
                WHERE em.usuario = :usuario
                AND en.id is null
                AND em.activo = true
               ')
                ->setParameter('usuario', $usuario);
        return $qb->getResult();
    }
}
